version: 2

defaults: &defaults
  working_directory: ~/project/quasar-typescript
  docker:
    - image: circleci/node:8-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: yarn
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - quasar-typescript

  test-cover:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run unit tests and collect coverage
          command: yarn test:cover
      - run:
          name: Report coverage stats
          command: |
            if [[ -z $CIRCLE_PULL_REQUEST ]]; then
              ./node_modules/.bin/codecov
            fi

workflows:
  version: 2
  install_and_test:
    jobs:
      - install
      - test-cover:
          requires:
            - install

general:
  branches:
    only:
      - master
